name: Run Node.js Tests with Chrome

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install

    - name: Install dependencies for Chrome (for headless mode)
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libxss1 \
          libappindicator3-1 \
          libindicator7 \
          fonts-liberation \
          libnss3 \
          libgdk-pixbuf2.0-0 \
          libnspr4 \
          xdg-utils \
          wget \
          ca-certificates

    - name: Run tests
      run: npm test
      env:
        CI: true
